name: goal_management_app
description: "Flutter + Spring Boot 기반의 개인용 목표 관리 애플리케이션"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP 통신
  http: ^1.1.0
  
  # 상태 관리
  provider: ^6.1.1
  
  # 로컬 저장소
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # UI 컴포넌트
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # 유틸리티
  intl: ^0.19.0

  # Firebase 관련
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9

  # 알림
  flutter_local_notifications: ^17.2.3

  # 아이콘
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # 테스트 의존성
  mockito: ^5.4.4
  build_runner: ^2.4.7
  integration_test:
    sdk: flutter
  test: ^1.24.9

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/
  #   - icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic