[variables]
JAVA_VERSION = "21"

[phases.setup]
nixPkgs = ["openjdk21"]

[phases.build]
cmds = ["./gradlew clean build -x test"]

[start]
cmd = "java -jar $(find build/libs -name '*.jar' ! -name '*plain*' | head -1)"