# Supabase 로컬 테스트용 설정
spring:
  # Supabase PostgreSQL 설정
  datasource:
    url: jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres
    username: postgres.porszbvzgosxurnhrchp
    password: J8qih0ZWIvnLINZW
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      connection-timeout: 30000
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: validate  # 스키마가 이미 Supabase에 있으므로 validate만
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # SQL 초기화 비활성화 (Supabase에 이미 데이터 있음)
  sql:
    init:
      mode: never

# 로깅 설정 (개발용)
logging:
  level:
    com.goalapp: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# 서버 설정
server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: on_param