# 프로덕션 환경 설정 (영구 데이터 저장)
spring:
  application:
    name: goal-management-app
  
  # 데이터베이스 설정 (파일 기반 H2)
  datasource:
    url: jdbc:h2:file:./data/goaldb;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # H2 콘솔 설정
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update  # create-drop 대신 update 사용 (데이터 유지)
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    open-in-view: false
  
  # SQL 초기화 설정 (최초 1회만)
  sql:
    init:
      mode: never  # 데이터 유지를 위해 never로 설정
      data-locations: classpath:data.sql
      encoding: UTF-8
  
  # HTTP 인코딩 설정
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  
# 로깅 설정
logging:
  level:
    com.goalapp: INFO  # 프로덕션에서는 INFO
    org.springframework.web: INFO
    org.hibernate.SQL: INFO
    root: INFO
  file:
    name: logs/goal-management-app.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    console: '%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'

# 서버 설정
server:
  port: 8080
  address: 0.0.0.0

# 관리 엔드포인트 설정
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
